title = "hoe zit het?"
baseURL = "https://hoezithet.net/"
languageCode = "nl-be"
theme = "gohugo-theme-ananke"
pluralizelisttitles = "false"

MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"
Paginate = 10
PaginatePath = "pagina"
googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.svg"
  description = "Wiskunde zonder getreuzel."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-white"
  featured_image = "/images/logo.svg"
  recent_posts_number = 5
  posts_per_section = 3
  read_more_copy = "Lees meer"
  default_fill = "#ffffff"
  default_stroke = "#000000"
	default_image = "/images/default.svg"
  env = "production"
  images = ["/images/logo.png"]


[outputFormats]
  [outputFormats.Bare]
  mediaType = "text/html"
  path = "bare"
  isHTML = true

[outputs]
  page = ["HTML", "Bare"]
