title = "hoe zit het?"
baseURL = "https://hoezithet.nu/"
languageCode = "nl-be"
theme = "gohugo-theme-ananke"
pluralizelisttitles = "false"

MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"
Paginate = 10
PaginatePath = "pagina"
googleAnalytics = "UA-133189848-1"
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.png"
  description = "Wetenschap verlicht"
  facebook = "https://fb.me/hoezithet"
  instagram = "https://instagram.com"
  github = "https://github.com/florisdf/hoe-zit-het"
  background_color_class = "bg-near-white"
  featured_image = "/images/logo.png"
  recent_posts_number = 5
  posts_per_section = 3
  read_more_copy = "Lees meer"
  default_fill = "#ffffff"
  default_stroke = "#000000"
	default_image = "/images/default.png"
  env = "production"
  images = ["/images/logo.png"]

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false

[outputFormats]
  [outputFormats.Bare]
  mediaType = "text/html"
  path = "bare"
  isHTML = true

[outputs]
  page = ["HTML", "Bare"]
