baseURL = "https://hoezithet.nu/"
title = "Hoe Zit Het?"
languageCode = "nl-be"
pluralizelisttitles = "false"

MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"
Paginate = 10
PaginatePath = "pagina"
summaryLength = 30
googleAnalytics = "UA-133189848-1"
enableRobotsTXT = true
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.png"
  description = "Problemen wiskunde of fysica? Met de gratis uitleg op Hoe Zit Het? heb je de leerstof razendsnel onder de knie."
  facebook = "https://fb.me/hoezithet"
  baseURL = "https://hoezithet.nu/"
  company = "Hoe Zit Het? vzw"
  github = "https://github.com/florisdf/hoe-zit-het"
  background_color_class = "bg-near-white"
  featured_image = "/images/logo.png"
  recent_posts_number = 5
  posts_per_section = 3
  read_more_copy = "Lees meer"
  default_fill = "#ffffff"
  default_stroke = "#000000"
	default_image = "/images/default.png"
  env = "production"
  images = ["/images/logo.png"]
  [params.adsense]
	pub_id = "pub-3341140218430301"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
    
[outputFormats]
  [outputFormats.Bare]
    mediaType = "text/html"
    path = "bare"
    isHTML = true

[outputs]
  page = ["HTML", "Bare"]
